# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [4]:
import numpy as np

arr=np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [9]:
l1=[]
l2=[]

for i in range (5):
    x=int(input())
    l1.append(x)
for j in range(5):
    y=int(input())
    l2.append(y)
arr1=np.array(l1)
arr2=np.array(l2)

concat_array=np.concatenate((arr1,arr2))
print(concat_array)

sort_arr1=np.sort(arr1)
sort_arr2=np.sort(arr2)
print(sort_arr1)
print(sort_arr2)

4
2
1
5
3
10
8
6
9
7
[ 4  2  1  5  3 10  8  6  9  7]
[1 2 3 4 5]
[ 6  7  8  9 10]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size

for dimension:
array_name.ndim

for size
array_name.size

In [23]:
arr=np.arange(20).reshape((10,2))
dim=arr.ndim
size=arr.size
print("dimension:",dim)
print("size:",size)

dimension: 2
size: 20


# Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims


Code snippet for np.newaxis:
for row: array_name[np.newaxis, :]
for column : array_name[:, np.newaxis]

In [39]:
arr=np.arange(12)
print("1D array:",arr.shape)
print("2D array:")
x_arr=arr[np.newaxis, :]
print(x_arr.shape)

y_arr=arr[: ,np.newaxis]
print(y_arr.shape)

1D array: (12,)
2D array:
(1, 12)
(12, 1)


Code snippet for np.expand_dims:
for row: np.expand_dims(array_name, axis = 0)
for column: np.expand_dims(array_name, axis = 1) 

In [42]:
arr=np.arange(15)
print("1D array:",arr.shape)
print("2D array:")
x_arr=np.expand_dims(arr,axis=0)
print(x_arr.shape)

y_arr=np.expand_dims(arr,axis=1)
print(y_arr.shape)

1D array: (15,)
2D array:
(1, 15)
(15, 1)


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [51]:
arr1=np.array([2,4,6,8,0])
print(arr1)
arr2=np.array([1,3,5,7,9])
print(arr2)
print("Vertical stacking:\n", np.vstack((arr1,arr2)))
print("Horizontal stacking:\n", np.hstack((arr1,arr2)))

[2 4 6 8 0]
[1 3 5 7 9]
Vertical stacking:
 [[2 4 6 8 0]
 [1 3 5 7 9]]
Horizontal stacking:
 [2 4 6 8 0 1 3 5 7 9]


# Questions 6:
How to get unique items and counts of unique items?

In [62]:
arr=np.array([1,1,4,3,1,5,2,4,1,5,2,4,3,5,4,4,1,3])
item,count=np.unique(arr,return_counts=True)
print(np.asarray((item,count)).T)

[[1 5]
 [2 2]
 [3 3]
 [4 5]
 [5 3]]
